version: '2'
volumes:
  vendor:
services:
  php:
    container_name: openloyalty_backend
    image: divante/open-loyalty-fpm
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./dev/php/php.ini:/usr/local/etc/php/php.ini
      - '../backend:/var/www/openloyalty:delegated'
      - '../open-loyalty-framework:/var/www/open-loyalty-framework:delegated'
      - vendor:/var/www/openloyalty/vendor # replace vendor folder at local by persisten mount volume
  nginx:
    container_name: openloyalty_frontend
    image: divante/open-loyalty-web
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./nginx/frontend.conf:/etc/nginx/conf.d/front.conf
      - ./config.js:/var/www/openloyalty/front/config.js
    links:
      - php
    ports:
      - '80:80'
      # - '8182:3001'
      # - '8183:3002'
      # - '8184:3003'
  elk:
    container_name: openloyalty_elk
    image: divante/open-loyalty-elasticsearch:2.2.0
  db:
    container_name: openloyalty_db
    image: postgres:9
    volumes:
      - ./datadir:/var/lib/postgresql/data
    env_file:
      - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    # ports:
    #   - '8186:8025'
